;自定义配置项, 游戏需要根据各自情况修改

;正式环境与测试环境选择，test为测试环境, release为正式环境
MSDK_ENV=test
;MSDK_ENV=release

; MSDK可选模块功能开关

; MSDK公告系统开关
needNotice=true
; MSDK公告系统公告自动拉取时间，单位为分钟（游戏可以设置的最小时间粒度为5分钟）
noticeTime=10

;MSDK PUSH系统开关
PUSH=true

; SAVE_UPDATE
SAVE_UPDATE=false

;渠道放量开关
GRAY_TEST_SWITCH=false

;实名认证回调开关 0或者1是调用msdk定制实名注册界面
MSDK_REAL_NAME_AUTH_SWITCH=1

;MSDKLog开关 0：不打印；1：logcat打印；2：打印到本地文件；3：logcat和本地文件同时打印；本地打印的保存在/sdcard/Android/data/游戏包名/files/MSDK
localLog=3

;灯塔和MTA、QQ日志开关，设为true时会打印详细日志，正式上线时建议将此开关关闭即设为false
STAT_LOG=false
;STAT_LOG=false

;MSDK Weixin Token自动刷新开关
WXTOKEN_REFRESH=true

;关闭bugly上报开关，默认应将其设为false，设为true即关闭了crash上报功能
CLOSE_BUGLY_REPORT=false

;关闭bugly上报crash回调开关&error回调开关，默认应将其设为false，设为true即关闭了crash回调&error回调开关
CLOSE_BUGLY_CALLBACK=false

;敏感字段采集开关配置，此处为不允许采集的敏感字段列表，默认将其设为空，目前针对字段AndroidID,Imei,Apn,QImei,QImei36
MSDK_DENIED_COLLECT_LIST =

;灯塔上报开关，默认应将其设为false，设为true即关闭了灯塔上报功能
CLOSE_BEACON_REPORT=false

;HttpDns开关，默认应将其设为false，设为true即关闭了HttpDns功能
CLOSE_HTTPDNS=false

;定位超时时间单位为毫秒
locationTimeOut=4000

;SCOPE=scope_what_you_want
SCOPE=scope_what_you_want

;ipv6_support开关
IPV6_SUPPORT=false

;V2签名开关，启用v2签名则打开如下开关（不打开会导致渠道号读取失败），默认关闭
V2SIGNING_ENABLED=true
;V3签名开关，启用v3签名则打开如下开关（不打开可能会导致渠道号读取失败），默认关闭
V3SIGNING_ENABLED=false

;信鸽厂商渠道配置，发布版本默认关闭，如果开启，请设置相应渠道的appId和appKey，华为渠道在Manifest配置
XG_OTHER_PUSH_ENABLE=true
XG_OTHER_PUSH_MEIZU_APPID=127836
XG_OTHER_PUSH_MEIZU_APPKEY=584eb9db1c3e4025ae96be51c0962598
XG_OTHER_PUSH_OPPO_APPID=78e372ad543c49db9eb7494b2bdb9d02
XG_OTHER_PUSH_OPPO_APPSECRET=c2eda10785a7402ea6ccaf179a9cc9db

;信鸽联合保活能力配置, 默认关闭
XG_PULL_UP_OTHER_APP_ENABLE = false

;信鸽accessId及accessKey设置，优先级高于xml内的配置
XG_V2_ACCESS_ID=1580002756
XG_V2_ACCESS_KEY=A06RWNK5XUHV


;打开注销账号页面的url，分为正式环境和测试环境
DELETE_ACCOUNT_URL_TEST=https://gacc-account-web-test.odp.qq.com/writeoff.html
DELETE_ACCOUNT_URL_RELEASE=https://gacc-account-web.odp.qq.com/writeoff.html

